kind: Service
apiVersion: v1
metadata:
  name: emp-management-service-app
  labels:
    name: emp-management-service-app
spec:
  ports:
    - nodePort: 30163
      port: 8082
      targetPort: 8082
      protocol: TCP
  selector:
    app: emp-management-service-app
  type: NodePort

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: emp-management-service-app
spec:
  selector:
    matchLabels:
      app: emp-management-service-app
  replicas: 1
  template:
    metadata:
      labels:
        app: emp-management-service-app
    spec:
      containers:
        - name: emp-management-service-app
          image: emp-management-service-app:1.0.3
          ports:
            - containerPort: 8082
          env: # Setting Enviornmental Variables
            - name: DB_HOST   # Setting Database host address from configMap
              valueFrom:
                configMapKeyRef:
                  name: postgres-conf  # name of configMap
                  key: host
            - name: DB_NAME  # Setting Database name from configMap
              valueFrom:
                configMapKeyRef:
                  name: postgres-conf
                  key: name
            - name: POSTGRES_USER  # Setting Database username from Secret
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials # Secret Name
                  key: postgres_user
            - name: POSTGRES_PASSWORD # Setting Database password from Secret
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: postgres_password

